#!/bin/bash

DATA_FILE="data.json"

# Pull raw fields: name, height (dm), weight (hg), first type
read NAME HEIGHT_DM WEIGHT_HG TYPE <<<"$(jq -r \
  '[.name, .height, .weight, .types[0].type.name] | @tsv' "$DATA_FILE")"

# Format and print the sentence
awk -v n="$NAME" -v h="$HEIGHT_DM" -v w="$WEIGHT_HG" -v t="$TYPE" '
BEGIN {
  # Capitalize the first letter of name and type
  n = toupper(substr(n,1,1)) substr(n,2)
  t = toupper(substr(t,1,1)) substr(t,2)
  printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", \
         n, t, w/10, h/10
}'
